apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32080
    - name: https
      port: 443
      targetPort: 8080
      nodePort: 32443
  selector:
    app.kubernetes.io/name: argocd-server
