apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-report-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-report
  template:
    metadata:
      labels:
        app: flask-report
        version: "v2.4.15" # reporttest branch
    spec:
      containers:
      - name: flask-report
        image: tvilarim/flask-app-image:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        env:
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
        - name: FLASK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: secret-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: uploads
        emptyDir: {}
