apiVersion: v1
kind: Service
metadata:
  name: flask-report-service
  labels:
    app: flask-report
spec:
  type: LoadBalancer
  selector:
    app: flask-report
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
