apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
        version: "v2.4.7" #With extraced text and search bar
    spec:
      containers:
      - name: flask-app
        image: tvilarim/flask-app-image:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: uploads
        emptyDir: {}
